/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import Login.EventCallBack;
import Login.EventTextField;
import Model.Customer;
import Model.Customer_Modify;
import Model.Item;
import Model.Item_Modify;
import Model.Order;
import Model.Order_Modify;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.util.Date;

/**
 *
 * @author anhng
 */
public class Order_Edit extends javax.swing.JPanel {
List<Customer> customerList = new ArrayList<>();
static int totaltotal=0;

static int cusID;
DefaultTableModel tableModel;

        
    /**
     * Creates new form Order_Edit
     */
    public Order_Edit() {
        initComponents();
        
        tableModel = (DefaultTableModel) table1.getModel();
        text_Price.setText("");
        
        
        
        showProductCombobox();
        Search();
        
    }

    public void showDH(){
        Order order = Order_Modify.getOrderDH();
        String dh = String.valueOf(order.getOrder_DH());
        String num = dh.substring(2);
        int num1 = Integer.valueOf(num);
        num1+=1;
        text_Order.setText("OD"+num1);
        text_Date.setText(java.time.LocalDate.now()+"");
    }
    
    public void caltotal(int mon){
        totaltotal=totaltotal+mon;
    }
    
    public void showOrder(){
        String orderdh = text_Order.getText();
       List<Order> orderList = Order_Modify.findByName(orderdh);
       
        tableModel.setRowCount(0);
        orderList.forEach((order) -> {
            Item item = Item_Modify.getItemId(order.getItem_ID());
            int price = item.getPrice();
            int num = order.getNumber();
            int total = price*num;
            tableModel.addRow(new Object[]{item.getItem_Name(),order.getNumber(),total});
        });
        
    }
    
    
    
    
    public void showProductCombobox(){
        
       List<Item> itemList = Item_Modify.findAll();
      
       for(Item item :itemList){
           product_cbb.addItem(item.getItem_Name());
        }
    }
    
    
    
    private void Search(){
        SearchTextField.addEvent(new EventTextField() {
            @Override
            public void onPressed(EventCallBack call) {
               String input = SearchTextField.getText();
               
        if (input != null && input.length() > 0){
            
            
            customerList = Customer_Modify.findByPhone(input);
            for(Customer customer :customerList){
                text_Name.setText(customer.getCustomerName());
            text_Phone.setText(customer.getCustomerPhone());
            cusID = customer.getCustomer_ID();
        }
        }  
       

            }

            @Override
            public void onCancel() {
                SearchTextField.setText("");
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        product_cbb = new com.raven.swing.Combobox<>();
        text_Price = new com.raven.swing.TextField();
        text_TotalMoney = new com.raven.swing.TextField();
        text_Number1 = new com.raven.swing.TextField();
        text_Date = new com.raven.swing.TextField();
        SearchTextField = new Login.TextFieldAnimation();
        text_Phone = new com.raven.swing.TextField();
        text_Name = new com.raven.swing.TextField();
        text_Order = new com.raven.swing.TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new com.raven.swing.table.Table();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        NewOrder_btn = new javax.swing.JButton();
        Reset_btn = new javax.swing.JButton();
        Save_btn = new javax.swing.JButton();
        Print_btn = new javax.swing.JButton();

        setBackground(new java.awt.Color(230, 230, 230));

        product_cbb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        product_cbb.setLabeText("Product");
        product_cbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_cbbActionPerformed(evt);
            }
        });

        text_Price.setEditable(false);
        text_Price.setBackground(new java.awt.Color(255, 255, 255));
        text_Price.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text_Price.setLabelText("Giá");
        text_Price.setLineColor(new java.awt.Color(0, 0, 0));

        text_TotalMoney.setEditable(false);
        text_TotalMoney.setBackground(new java.awt.Color(255, 255, 255));
        text_TotalMoney.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text_TotalMoney.setLabelText("Total money");
        text_TotalMoney.setLineColor(new java.awt.Color(0, 0, 0));

        text_Number1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text_Number1.setLabelText("Amount");
        text_Number1.setLineColor(new java.awt.Color(0, 0, 0));
        text_Number1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_Number1ActionPerformed(evt);
            }
        });

        text_Date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text_Date.setLabelText("Date buy");
        text_Date.setLineColor(new java.awt.Color(0, 0, 0));

        text_Phone.setEditable(false);
        text_Phone.setBackground(new java.awt.Color(255, 255, 255));
        text_Phone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text_Phone.setLabelText("Phone Number");
        text_Phone.setLineColor(new java.awt.Color(0, 0, 0));

        text_Name.setEditable(false);
        text_Name.setBackground(new java.awt.Color(255, 255, 255));
        text_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text_Name.setLabelText("Customer Name");
        text_Name.setLineColor(new java.awt.Color(0, 0, 0));

        text_Order.setEditable(false);
        text_Order.setBackground(new java.awt.Color(255, 255, 255));
        text_Order.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text_Order.setLabelText("Order ID");

        jScrollPane1.setBorder(null);

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Item", "Number", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        table1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table1);

        TextArea.setEditable(false);
        TextArea.setColumns(20);
        TextArea.setRows(5);
        jScrollPane2.setViewportView(TextArea);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(4, 72, 210));
        jLabel1.setText("ORDER");

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);

        NewOrder_btn.setBackground(new java.awt.Color(255, 255, 255));
        NewOrder_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NewOrder_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Add.png"))); // NOI18N
        NewOrder_btn.setText("New Order");
        NewOrder_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewOrder_btnActionPerformed(evt);
            }
        });
        jToolBar1.add(NewOrder_btn);

        Reset_btn.setBackground(new java.awt.Color(255, 255, 255));
        Reset_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Reset_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Refresh.png"))); // NOI18N
        Reset_btn.setText("Reset");
        Reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset_btnActionPerformed(evt);
            }
        });
        jToolBar1.add(Reset_btn);

        Save_btn.setBackground(new java.awt.Color(255, 255, 255));
        Save_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Save_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Save.png"))); // NOI18N
        Save_btn.setText("Save");
        Save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save_btnActionPerformed(evt);
            }
        });
        jToolBar1.add(Save_btn);

        Print_btn.setBackground(new java.awt.Color(255, 255, 255));
        Print_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Print_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/List.png"))); // NOI18N
        Print_btn.setText("Print Receipt");
        Print_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Print_btnActionPerformed(evt);
            }
        });
        jToolBar1.add(Print_btn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(product_cbb, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_Order, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_Number1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_TotalMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(text_Order, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(product_cbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text_Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text_Number1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text_TotalMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jScrollPane2)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void product_cbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_cbbActionPerformed
        // TODO add your handling code here:
        String price = product_cbb.getSelectedItem().toString(); //get bonus level
        
        Item item = Item_Modify.getItemName(price); //get bonus
        text_Price.setText(String.valueOf(item.getPrice())); 
        
    }//GEN-LAST:event_product_cbbActionPerformed

    private void text_Number1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_Number1ActionPerformed
        // TODO add your handling code here:
        int number = Integer.valueOf(text_Number1.getText());
        int price = Integer.valueOf(text_Price.getText());
        int total = number*price;
        
        text_TotalMoney.setText(String.valueOf(total));
        
    }//GEN-LAST:event_text_Number1ActionPerformed

    private void Reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset_btnActionPerformed
        // TODO add your handling code here:
        tableModel.setRowCount(0);
        text_Order.setText("");
        text_Price.setText("");
        text_Number1.setText("");
        text_Date.setText("");
        text_TotalMoney.setText("");
        TextArea.setText("");
    }//GEN-LAST:event_Reset_btnActionPerformed

    private void NewOrder_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewOrder_btnActionPerformed
        // TODO add your handling code here:
        showDH();
        
        
    }//GEN-LAST:event_NewOrder_btnActionPerformed

    private void Save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_btnActionPerformed
        // TODO add your handling code here:
        String date = text_Date.getText();
        int customerID = cusID;
        String itemname = product_cbb.getSelectedItem()+"";
        Item item = Item_Modify.getItemName(itemname);
        int itemid = item.getItem_ID();
        int number = Integer.valueOf(text_Number1.getText());
        String orderid = text_Order.getText();
        Order order = new Order(date, customerID, itemid, number, orderid);
        Order_Modify.insert(order);
        
        showOrder();
        text_Price.setText("");
        text_Number1.setText("");
        
        text_TotalMoney.setText("");
        text_Date.setText(java.time.LocalDate.now()+"");
    }//GEN-LAST:event_Save_btnActionPerformed

    private void Print_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Print_btnActionPerformed
        // TODO add your handling code here:
        TextArea.setText("****************************************************************\n");
        TextArea.setText(TextArea.getText()+"*                             UIT COMPANY                             *\n");
        TextArea.setText(TextArea.getText()+"*                          Thu Duc - TP.HCM                          *\n");
        TextArea.setText(TextArea.getText()+"*                        Phone Number: 09876541323                        *\n");
        TextArea.setText(TextArea.getText()+"****************************************************************\n");
        
        
        TextArea.setText(TextArea.getText()+text_Date.getText()+"\n");
        TextArea.setText(TextArea.getText()+"Customer Name: "+text_Name.getText()+"\n");
        TextArea.setText(TextArea.getText()+"Customer Phone: "+text_Phone.getText()+"\n");
        TextArea.setText(TextArea.getText()+"----------------------------------------------------------------------------\n");
        
        String orderdh = text_Order.getText();
       List<Order> orderList = Order_Modify.findByName(orderdh);
       
       
        orderList.forEach((order) -> {
            Item item = Item_Modify.getItemId(order.getItem_ID());
            int price = item.getPrice();
            int num = order.getNumber();
            int total = price*num;
            
            TextArea.setText(TextArea.getText()+item.getItem_Name()+"\n"+"*                                            "+order.getNumber()+"                          "+total+"\n"+"----------------------------------------------------------------------------"+"\n");
            caltotal(total);
           
        });
        
        TextArea.setText(TextArea.getText()+"                                                     Total Money: "+totaltotal+"\n");
        TextArea.setText(TextArea.getText()+"Thank you dear customer !!!");
        
    }//GEN-LAST:event_Print_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NewOrder_btn;
    private javax.swing.JButton Print_btn;
    private javax.swing.JButton Reset_btn;
    private javax.swing.JButton Save_btn;
    private Login.TextFieldAnimation SearchTextField;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private com.raven.swing.Combobox<String> product_cbb;
    private com.raven.swing.table.Table table1;
    private com.raven.swing.TextField text_Date;
    private com.raven.swing.TextField text_Name;
    private com.raven.swing.TextField text_Number1;
    private com.raven.swing.TextField text_Order;
    private com.raven.swing.TextField text_Phone;
    private com.raven.swing.TextField text_Price;
    private com.raven.swing.TextField text_TotalMoney;
    // End of variables declaration//GEN-END:variables
}
