/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import Model.Item;
import Model.Order;
import Model.Order_Modify;
import Model.Receipt;
import Model.Receipt_Modify;
import Model.Staff;
import Model.Staff_Modify;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anhng
 */
public class Receipt_Edit extends javax.swing.JPanel {
    DefaultTableModel tableModel;
    Calendar cal = new GregorianCalendar();
    
    
    public Receipt_Edit() {
        initComponents();
        tableModel = (DefaultTableModel) table1.getModel();
        showReceipt();
        showOrderCombobox();
        showEmployeeCombobox();
    }
    
    public void showReceipt() {
        List<Receipt> receiptList = Receipt_Modify.findAll();
        tableModel.setRowCount(0);
        receiptList.forEach((rec) -> {
            tableModel.addRow(new Object[]{rec.getReceipt_ID(),rec.getDateReceipt(),rec.getDatePrintReceipt(),rec.getOrder_ID(),rec.getEmployee_ID()});
        });
    }

    public void showOrderCombobox(){
       List<Order> orderList = Order_Modify.findAll();
       
       for(Order order : orderList){
           combobox_Order.addItem((order.getOrder_ID()+""));
        }
    }
    
    public void showEmployeeCombobox(){
       List<Staff> staffList = Staff_Modify.findAll();
       
       for(Staff staff : staffList){
           combobox_Employee.addItem((staff.getId()+""));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchTextField = new Login.TextFieldAnimation();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        button_Fix = new com.raven.swing.ButtonGradient();
        button_Submit = new com.raven.swing.ButtonGradient();
        button_Insert = new com.raven.swing.ButtonGradient();
        Text_ReceiptID = new com.raven.swing.TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new com.raven.swing.table.Table();
        button_Cancle = new com.raven.swing.ButtonGradient();
        Text_Date = new com.raven.swing.TextField();
        combobox_Order = new com.raven.swing.Combobox<>();
        combobox_Employee = new com.raven.swing.Combobox<>();
        Text_DatePrint = new com.raven.swing.TextField();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(76, 76, 76));
        jLabel5.setText("Data Item");
        jLabel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        button_Fix.setBackground(new java.awt.Color(255, 255, 255));
        button_Fix.setText("FIX");
        button_Fix.setColor1(new java.awt.Color(194, 85, 1));
        button_Fix.setColor2(new java.awt.Color(255, 212, 99));
        button_Fix.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button_Fix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_FixActionPerformed(evt);
            }
        });

        button_Submit.setText("SUBMIT");
        button_Submit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_SubmitActionPerformed(evt);
            }
        });

        button_Insert.setBackground(new java.awt.Color(255, 255, 255));
        button_Insert.setText("INSERT");
        button_Insert.setColor1(new java.awt.Color(194, 85, 1));
        button_Insert.setColor2(new java.awt.Color(255, 212, 99));
        button_Insert.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button_Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_InsertActionPerformed(evt);
            }
        });

        Text_ReceiptID.setEditable(false);
        Text_ReceiptID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Text_ReceiptID.setLabelText("Receipt ID");

        jScrollPane1.setBorder(null);

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Receipt_ID", "Date Receipt", "Date Print", "Order_ID", "Employee"
            }
        ));
        table1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        table1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table1);

        button_Cancle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button_Cancle.setLabel("CANCLE");
        button_Cancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_CancleActionPerformed(evt);
            }
        });

        Text_Date.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Text_Date.setLabelText("DATE");

        combobox_Order.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        combobox_Order.setLabeText("ORDER");

        combobox_Employee.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        combobox_Employee.setLabeText("EMPLOYEE");

        Text_DatePrint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Text_DatePrint.setLabelText("DATE PRINT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Text_ReceiptID, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(337, 337, 337)
                                                .addComponent(combobox_Order, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(button_Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(button_Insert, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(101, 101, 101)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(button_Fix, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(button_Cancle, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(52, 52, 52)
                                                .addComponent(Text_DatePrint, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(Text_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combobox_Employee, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Text_ReceiptID, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combobox_Order, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(combobox_Employee, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(Text_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(Text_DatePrint, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button_Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_Fix, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button_Insert, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_Cancle, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 15, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button_FixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_FixActionPerformed
        int row = table1.getSelectedRow();
        button_Insert.setVisible(false);
        int receiptId= Integer.valueOf(String.valueOf(table1.getValueAt(row, 0))); // lấy đc id
        Receipt receipt = Receipt_Modify.getReceiptbyId(receiptId);

        Text_ReceiptID.setText(String.valueOf(receipt.getReceipt_ID()));
        Text_DatePrint.setText(String.valueOf(receipt.getDatePrintReceipt()));
        Text_Date.setText(String.valueOf(receipt.getDateReceipt()));
        
        
        
    }//GEN-LAST:event_button_FixActionPerformed

    private void button_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_SubmitActionPerformed
        int Id = Integer.valueOf(Text_ReceiptID.getText());
        int order = Integer.valueOf(combobox_Order.getSelectedItem().toString());
        int employee = Integer.valueOf(combobox_Employee.getSelectedItem().toString());
        
        String date = Text_Date.getText();
        String dateprint = Text_DatePrint.getText();

        Receipt receipt = new Receipt(Id,date, dateprint,order, employee);
        
        
        Receipt_Modify.update(receipt);
        showReceipt();
        
        Text_ReceiptID.setText("");
        Text_Date.setText("");
        Text_DatePrint.setText("");
    }//GEN-LAST:event_button_SubmitActionPerformed

    private void button_InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_InsertActionPerformed
        int order = Integer.valueOf(combobox_Order.getSelectedItem().toString());
        int employee = Integer.valueOf(combobox_Employee.getSelectedItem().toString());
        
        String date = Text_Date.getText();
        String dateprint = Text_DatePrint.getText();

        Receipt receipt = new Receipt(date, dateprint,order, employee);
        Receipt_Modify.insert(receipt);
        showReceipt();
        
        Text_ReceiptID.setText("");
        Text_Date.setText("");
        Text_DatePrint.setText("");
        
    }//GEN-LAST:event_button_InsertActionPerformed

    private void button_CancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_CancleActionPerformed
        button_Insert.setVisible(true);
        button_Fix.setVisible(true);
        Text_ReceiptID.setText("");
        Text_DatePrint.setText("");
        Text_Date.setText("");
        
    }//GEN-LAST:event_button_CancleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Login.TextFieldAnimation SearchTextField;
    private com.raven.swing.TextField Text_Date;
    private com.raven.swing.TextField Text_DatePrint;
    private com.raven.swing.TextField Text_ReceiptID;
    private com.raven.swing.ButtonGradient button_Cancle;
    private com.raven.swing.ButtonGradient button_Fix;
    private com.raven.swing.ButtonGradient button_Insert;
    private com.raven.swing.ButtonGradient button_Submit;
    private com.raven.swing.Combobox<String> combobox_Employee;
    private com.raven.swing.Combobox<String> combobox_Order;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.raven.swing.table.Table table1;
    // End of variables declaration//GEN-END:variables
}
