/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Admin
 */
public class Changepassword_Screen extends javax.swing.JFrame {

    /**
     * Creates new form Changepassword_Screen
     */
    public Changepassword_Screen() {
        initComponents();
          Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_close.setBorder(label_border);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextField_username = new javax.swing.JTextField();
        jLabel_username = new javax.swing.JLabel();
        jLabel_password = new javax.swing.JLabel();
        jTextField_password = new javax.swing.JTextField();
        jLabel_confirmpassword = new javax.swing.JLabel();
        jTextField_confirmpassword = new javax.swing.JTextField();
        jButton_confirmchangepass = new javax.swing.JButton();
        jLabel_close = new javax.swing.JLabel();

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 51)));

        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTextField_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_usernameFocusLost(evt);
            }
        });
        jTextField_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_usernameKeyTyped(evt);
            }
        });

        jLabel_username.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_username.setText("Username");

        jLabel_password.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_password.setText("New password");

        jTextField_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_passwordFocusLost(evt);
            }
        });
        jTextField_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_passwordKeyTyped(evt);
            }
        });

        jLabel_confirmpassword.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_confirmpassword.setText("Confirm password");

        jTextField_confirmpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_confirmpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_confirmpasswordFocusLost(evt);
            }
        });
        jTextField_confirmpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_confirmpasswordKeyTyped(evt);
            }
        });

        jButton_confirmchangepass.setBackground(new java.awt.Color(0, 84, 140));
        jButton_confirmchangepass.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 11)); // NOI18N
        jButton_confirmchangepass.setForeground(new java.awt.Color(255, 255, 255));
        jButton_confirmchangepass.setText("Change password");
        jButton_confirmchangepass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_confirmchangepassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_confirmchangepassMouseExited(evt);
            }
        });
        jButton_confirmchangepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_confirmchangepassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_confirmpassword)
                            .addComponent(jLabel_password))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton_confirmchangepass, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_confirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel_username)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_username)
                    .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_password))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_confirmpassword)
                    .addComponent(jTextField_confirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_confirmchangepass)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_close.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setText("X");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel_close)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseExited
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_close.setBorder(label_border);
        jLabel_close.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_closeMouseExited

    private void jLabel_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseEntered
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_close.setBorder(label_border);
        jLabel_close.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_closeMouseEntered

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        this.dispose();
          Login_Screen login =new Login_Screen();
                 login.setVisible(true);
            
                
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jButton_confirmchangepassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_confirmchangepassMouseEntered
          jButton_confirmchangepass.setBackground(new Color(0,101,183));
    }//GEN-LAST:event_jButton_confirmchangepassMouseEntered

    private void jButton_confirmchangepassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_confirmchangepassMouseExited
         jButton_confirmchangepass.setBackground(new Color(0,84,104));
    }//GEN-LAST:event_jButton_confirmchangepassMouseExited

    private void jButton_confirmchangepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_confirmchangepassActionPerformed
        String username,password,confirmpassword;
        username=jTextField_username.getText();
        password=jTextField_password.getText();
        confirmpassword=jTextField_confirmpassword.getText();
        if(username.equals("") || password.equals("") || confirmpassword.equals("")){
             JOptionPane.showMessageDialog(null,"Please fill all the information","Changepassword Error",2);
        } 
        else if (!(password.equals(confirmpassword)) ){
            
         JOptionPane.showMessageDialog(null,"Password and Confirm Password must be the same","Confirm Password Error",2);
        } else if(password.equals(confirmpassword)) {
            // check username exist
            PreparedStatement st1;
            ResultSet rs;
            String querycheckusername= "SELECT * FROM `user` WHERE `USERNAME`= ?  ";
             try {
            st1= My_CNX.getConnection().prepareStatement(querycheckusername);
            st1.setString(1, username);
            rs =st1.executeQuery();
            if(rs.next()){
               // update password
            PreparedStatement st2;
            String query= "UPDATE `user` SET `PASSWORD`=? WHERE `USERNAME` =? ";
           try {
            st2= My_CNX.getConnection().prepareStatement(query);
            st2.setString(1, Login_Screen.md5(password));
            st2.setString(2,username);
            st2.execute();
            JOptionPane.showMessageDialog(null,"Change Password Success","",2);
            jTextField_username.setText("");
            jTextField_password.setText("");
            jTextField_confirmpassword.setText("");
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Login_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
                 
              
                 
                 
            } else{
                JOptionPane.showMessageDialog(null,"Invalid Username","Change Password Error",2);
                jTextField_username.setText("");
                jTextField_password.setText("");
                jTextField_confirmpassword.setText("");
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Login_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
            
           
            
           
       
        }
    }//GEN-LAST:event_jButton_confirmchangepassActionPerformed

    private void jTextField_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_usernameFocusGained
        jLabel_username.setForeground(Color.red);
    }//GEN-LAST:event_jTextField_usernameFocusGained

    private void jTextField_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_usernameFocusLost
        jLabel_username.setForeground(Color.black);
    }//GEN-LAST:event_jTextField_usernameFocusLost

    private void jTextField_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_passwordFocusGained
        jLabel_password.setForeground(Color.red);
    }//GEN-LAST:event_jTextField_passwordFocusGained

    private void jTextField_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_passwordFocusLost
         jLabel_password.setForeground(Color.black);
    }//GEN-LAST:event_jTextField_passwordFocusLost

    private void jTextField_confirmpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_confirmpasswordFocusGained
        jLabel_confirmpassword.setForeground(Color.red);
    }//GEN-LAST:event_jTextField_confirmpasswordFocusGained

    private void jTextField_confirmpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_confirmpasswordFocusLost
         jLabel_confirmpassword.setForeground(Color.black);
    }//GEN-LAST:event_jTextField_confirmpasswordFocusLost

    private void jTextField_passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_passwordKeyTyped
         if (jTextField_password.getText().length() > 10 ){
              JOptionPane.showMessageDialog(null,"Password  must be less than 10 characters ","",2);
         } 
    }//GEN-LAST:event_jTextField_passwordKeyTyped

    private void jTextField_confirmpasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_confirmpasswordKeyTyped
         if (jTextField_confirmpassword.getText().length() > 10 ){
              JOptionPane.showMessageDialog(null,"Password  must be less than 10 characters ","",2);
         } 
    }//GEN-LAST:event_jTextField_confirmpasswordKeyTyped

    private void jTextField_usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_usernameKeyTyped
        if (jTextField_username.getText().length() > 10 ){
              JOptionPane.showMessageDialog(null,"Password  must be less than 10 characters ","",2);
         } 
    }//GEN-LAST:event_jTextField_usernameKeyTyped
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Changepassword_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Changepassword_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Changepassword_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Changepassword_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Changepassword_Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_confirmchangepass;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_confirmpassword;
    private javax.swing.JLabel jLabel_password;
    private javax.swing.JLabel jLabel_username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField_confirmpassword;
    private javax.swing.JTextField jTextField_password;
    private javax.swing.JTextField jTextField_username;
    // End of variables declaration//GEN-END:variables
}
